version: '3.1'

services:
  app:
    build: .
    ports:
      - "8080:80"  # Пробрасываем порт для приложения (локальный 8080 -> контейнерный 80)
    environment:
      - ASPNETCORE_URLS=http://+:80  # Для работы приложения на порту 80

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Pashok0103
      MYSQL_DATABASE: peskostruyka
      MYSQL_USER: root
      MYSQL_PASSWORD: Pashok0103
    ports:
      - "3306:3306"  # Пробрасываем порт для MySQL
    volumes:
      - ./data:/var/lib/mysql
