version: '3.1'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Pashok0103
      MYSQL_DATABASE: peskostruyka
      MYSQL_USER: root
      MYSQL_PASSWORD: Pashok0103
    ports:
      - "3306:3306"
      - "80:80"
    volumes:
      - ./data:/var/lib/mysql
